apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: media-memcached
  name: media-memcached
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: media-memcached
    spec:
      containers:
      - image: memcached
        name: media-memcached
        resources: {}
      hostname: media-memcached
      restartPolicy: Always
status: {}
