apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: post-storage-mongodb
  name: post-storage-mongodb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: post-storage-mongodb
    spec:
      containers:
      - image: mongo
        name: post-storage-mongodb
        resources: {}
      hostname: post-storage-mongodb
      restartPolicy: Always
status: {}
