apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: social-graph-mongodb
  name: social-graph-mongodb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: social-graph-mongodb
    spec:
      containers:
      - image: mongo
        name: social-graph-mongodb
        resources: {}
      hostname: social-graph-mongodb
      restartPolicy: Always
status: {}
