apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: text-service
  name: text-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: text-service
    spec:
      containers:
      - command:
        - TextService
        image: yg397/social-network-microservices
        name: text-service
        resources: {}
      hostname: text-service
      restartPolicy: Always
status: {}
