apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: user-timeline-redis
  name: user-timeline-redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: user-timeline-redis
    spec:
      containers:
      - image: redis
        name: user-timeline-redis
        resources: {}
      hostname: user-timeline-redis
      restartPolicy: Always
status: {}
